<?php if (!defined('ABSPATH')) exit; // Exit if accessed directly
$codes = array(
    array('code' => 'appointment_date', 'description' => esc_html__('date of appointment', 'bookme_pro')),
    array('code' => 'appointment_time', 'description' => esc_html__('time of appointment', 'bookme_pro')),
    array('code' => 'appointment_end_date', 'description' => esc_html__('end date of appointment', 'bookme_pro')),
    array('code' => 'appointment_end_time', 'description' => esc_html__('end time of appointment', 'bookme_pro')),
    array('code' => 'booking_number', 'description' => esc_html__('booking number', 'bookme_pro')),
    array('code' => 'approve_appointment_url', 'description' => esc_html__('URL of approve appointment link (to use inside <a> tag)', 'bookme_pro')),
    array('code' => 'cancel_appointment_url', 'description' => esc_html__('URL of cancel appointment link (to use inside <a> tag)', 'bookme_pro')),
    array('code' => 'category_name', 'description' => esc_html__('name of category', 'bookme_pro')),
    array('code' => 'client_email', 'description' => esc_html__('email of client', 'bookme_pro')),
    array('code' => 'client_name', 'description' => esc_html__('full name of client', 'bookme_pro')),
    array('code' => 'client_first_name', 'description' => esc_html__('first name of client', 'bookme_pro')),
    array('code' => 'client_last_name', 'description' => esc_html__('last name of client', 'bookme_pro')),
    array('code' => 'client_phone', 'description' => esc_html__('phone of client', 'bookme_pro')),
    array('code' => 'company_name', 'description' => esc_html__('name of company', 'bookme_pro')),
    array('code' => 'company_address', 'description' => esc_html__('address of company', 'bookme_pro')),
    array('code' => 'company_phone', 'description' => esc_html__('company phone', 'bookme_pro')),
    array('code' => 'company_website', 'description' => esc_html__('company web-site address', 'bookme_pro')),
    array('code' => 'custom_fields', 'description' => esc_html__('combined values of all custom fields', 'bookme_pro')),
    array('code' => 'google_calendar_url', 'description' => esc_html__('URL for adding event to client\'s Google Calendar (to use inside <a> tag)', 'bookme_pro')),
    array('code' => 'number_of_persons', 'description' => esc_html__('number of persons', 'bookme_pro')),
    array('code' => 'payment_type', 'description' => esc_html__('payment type', 'bookme_pro')),
    array('code' => 'reject_appointment_url', 'description' => esc_html__('URL of reject appointment link (to use inside <a> tag)', 'bookme_pro')),
    array('code' => 'service_info', 'description' => esc_html__('info of service', 'bookme_pro')),
    array('code' => 'service_name', 'description' => esc_html__('name of service', 'bookme_pro')),
    array('code' => 'service_price', 'description' => esc_html__('price of service', 'bookme_pro')),
    array('code' => 'service_duration', 'description' => esc_html__('duration of service', 'bookme_pro')),
    array('code' => 'staff_email', 'description' => esc_html__('email of staff', 'bookme_pro')),
    array('code' => 'staff_name', 'description' => esc_html__('name of staff', 'bookme_pro')),
    array('code' => 'staff_phone', 'description' => esc_html__('phone of staff', 'bookme_pro')),
    array('code' => 'staff_info', 'description' => esc_html__('info of staff', 'bookme_pro')),
    array('code' => 'total_price', 'description' => esc_html__('total price of booking (sum of all cart items after applying coupon)', 'bookme_pro')),
);
BookmePro\Lib\Utils\Common::codes(BookmePro\Lib\Proxy\Shared::prepareNotificationCodesList($codes, 'customer'));
